### ISSUE TITLE
Create test file for all new extract files

### ISSUE THREAD

**Issue by NabihaMoh** [BerkayDur/sales-tracker-hermes#105]
**Todo**
- [x] Create a test file for extract_combined
- [x] Create a test file for extract_from_asos
- [x] Create a test file for helpers
