### ISSUE TITLE
Add Patagonia Extract to the ETL Pipeline

### ISSUE THREAD

**Issue by danfh00** [BerkayDur/sales-tracker-hermes#107]
**Todo**
- [ ] Extract the beautiful soup of the product page
- [ ] Extract the price
- [ ] Extract the sale status

**Story**
As a user, I would like to know if the products are on sale on Patagonia
