### ISSUE TITLE
Develop Roadmap

### ISSUE THREAD

**Issue by danfh00** [BerkayDur/sales-tracker-hermes#31]
### Steps
- [x] Define project milestones and deliverables
- [x] Create a timeline for each milestone
- [x] Document the roadmap and share it with the team

### User Story
As a project manager, I need a roadmap to plan and communicate the project timeline and milestones to the team.
