### ISSUE TITLE
Remove Product from Tracking

### ISSUE THREAD

**Issue by A-Faris** [BerkayDur/sales-tracker-hermes#34]
### Steps

- [x] Implement functionality in the Streamlit dashboard to view tracked products.
- [x] Develop a feature to remove a product from the tracking list.
- [x] Update the database to reflect the removal of the tracking request.

### User Story

As a user, I want to remove a product from my tracking list so that I no longer receive updates about it.
