### ISSUE TITLE
Get a list of verified emails for use in the dashboard

### ISSUE THREAD

**Issue by BerkayDur** [BerkayDur/sales-tracker-hermes#70]
**Todo**

- [x] Connect to ses using BOTO3.
- [x] Return all emails (verified or unverified).
- [x] Return the verified emails.

**Story**
As a developer, having access to which customers are verified will enable greater functionality on the dashboard, allowing for a better user experience.
