### ISSUE TITLE
Add email as unverified ses endpoint and send ses confirmation email.

### ISSUE THREAD

**Issue by BerkayDur** [BerkayDur/sales-tracker-hermes#72]
**Todo**

- [x] Connect to ses using BOTO3.
- [x] Add email to ses as an unverified email.
- [x] Send confirmation to email

**Story**
As a developer, letting customers sign up for email verifications will enable greater functionality (email notification), allowing for a better user experience!!
