### ISSUE TITLE
Update ETL terraform script to combine all the smaller terraform scripts for each part of the state machine's workflow.

### ISSUE THREAD

**Issue by BerkayDur** [BerkayDur/sales-tracker-hermes#74]
**Todo**

- [x] Add the Provisioning lambda terraform script to step function terraform script.
- [x] Add the ETL lambda terraform script to step function terraform script.
- [x] Add the Email lambda terraform script to step function terraform script.

**Story**
As a developer, being able to build and destroy infrastructure easily make it easier to make changes, allowing for easier development.
