### ISSUE TITLE
Update ERD to work with multiple websites

### ISSUE THREAD

**Issue by BerkayDur** [BerkayDur/sales-tracker-hermes#79]
The ERD currently has the support for multiple websites, but being more explicit by adding a new table could help move things along:

**Todo**
- [x] Confer with team about ERD diagram
- [x] Create a new issue and pull request to update the Schema.SQL
- [x] Create issues pull requests to update the previous sections to work with this new schema.
