### ISSUE TITLE
Update Global README.md

### ISSUE THREAD

**Issue by BerkayDur** [BerkayDur/sales-tracker-hermes#83]
**Todo**
- [ ] Research a few readme formats
- [ ] Update the global readme to be descriptive whilst being easy to understand
- [ ] Look at the nested directories and link their readme's in from the global readme
- [ ] Add the ERD, Architecture Diagram to Readme
- [ ] Add badges to the Readme.

••Story••
Making the readme better and more descriptive will make it easier for anyone to navigate the project page
