### ISSUE TITLE
Add Extraction of Websites To provision lambda

### ISSUE THREAD

**Issue by danfh00** [BerkayDur/sales-tracker-hermes#92]
**Todo**
- [x] Modify the extract query to join with the websites table
- [x] Extract the website for each product
- [x] Ensure the website is correctly sent to the transform lambda

**Story**
Including the website in the data sent to transform allows the updated cost data to be extracted correctly
